### ISSUE TITLE
How to compile this project in VS

### ISSUE THREAD

**Issue by CatOnTheHorizon** [nlitsme/idbutil#5]
Hello, I am new to building C++ projects. When attempting to build this project with VS2022 on Windows, I encountered some issues. Could you please add the third-party libraries and environment variables required for the project to the ReadMe for configuration purposes?

**Comment by nlitsme** [comment]
could you elaborate on 'some issues' ?

CMakeLists.txt  lists the dependencies: look for the 'find_package' lines.  These are all handled in the cmake_find/FindXXX.cmake  files.

Also, I don't think I ever tried building this on windows.

**Comment by CatOnTheHorizon** [comment]
Yes, as mentioned above, I am not proficient in C++ development, so I used VS to compile without configuring the IDASDK environment variables. Subsequently, I configured the IDASDK and added the cpputils module by reviewing the CMakeList file. Now, I have successfully compiled the binary executable file using VS2022. Thank you very much for your code.
